polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    # /polls
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /polls/question_id
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'choice'),
    url(r'^(?P<pk>[0-9]+)/result/$', views.ResultsView.as_view(), name = 'results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote')
]

projectISP/urls.py
from django.contrib import admin
from django.conf.urls import url,include 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data publihed')
    def __str__ (self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    def __str__ (self):
        return self.choice_text+ " [ " + str(self.vote) + " ]"

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponseRedirect
from .models import Question ,Choice
from django.utils import timezone 

# def question(request):
#     question = Question.objects.all()
#     data = { 'question' : question}
#     return render(request, 'polls/index.html', data)

# def get_queryset(self):
#     """
#     Return the last five published questions (not including those set to be
#     published in the future).
#     """
#     return Question.objects.filter(
#         pub_date__lte=timezone.localtime()
#     ).order_by('-pub_date')[:5]

# def choice(request, question_id):
#     question =get_object_or_404(Question, pk=question_id)
#     data ={'question': question}
#     return render(request, 'polls/detail.html', data)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
        pub_date__lte=timezone.localtime()
    ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.localtime())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else :
        selected_choice.vote += 1 
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>question</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}
    <strong>{{ error_message }}</strong>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name = "choice" id = "choice{{ forloop.counter }}" value= "{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value = "Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">   
    <title>index</title>
</head>
<body>
    {% if latest_question_list  %}
    <h1>Welcome!!!</h1>
    <h2>Question list</h2>
    {% for i in latest_question_list %}
       <a href="{% url 'polls:choice' i.id %}"><li><strong>{{ i }}</strong></li></a>
    {% endfor %}
    {% else %}
    <h1>No polls are available.</h1>
    {% endif %}
</body>
</html>

polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Show vote</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:choice' question.id %}">Vote again?</a>
</body>
</html>